name: Test

on:
  push:
    branches: [ main ]
  pull_request:

# Ensure we don't run multiple concurrent workflows on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Cache node_modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node22-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node22-modules-${{ github.event.pull_request.base.ref || 'main' }}
          ${{ runner.os }}-node22-modules-main
          ${{ runner.os }}-node22-modules-
    
    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Run Jest tests
      run: npm run test:ci -- --maxWorkers=4
    
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
        flag-name: unit-tests
        
  e2e-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node22-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node22-modules-${{ github.event.pull_request.base.ref || 'main' }}
            ${{ runner.os }}-node22-modules-main
            ${{ runner.os }}-node22-modules-
      
      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-node22-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node22-playwright-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node22-playwright-${{ github.event.pull_request.base.ref || 'main' }}
            ${{ runner.os }}-node22-playwright-main
            ${{ runner.os }}-node22-playwright-
      
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        env:
          CI: true
          VITE_ENABLE_COVERAGE: true
        run: npm run e2e:ci
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
      
      - name: Prepare coverage directories
        run: mkdir -p coverage/unit/temp coverage/e2e/tmp
      
      - name: Generate coverage report
        run: npx nyc report --reporter=lcov --reporter=json --report-dir=./coverage/e2e
      
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/e2e/lcov.info
          flag-name: e2e-tests 